services:
  mysql:
    container_name: spring_batch
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: "spring_batch"
      MYSQL_ROOT_PASSWORD: "1234"
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  pushgateway:
    image: prom/pushgateway:v1.6.2
    restart: always
    ports:
      - '9091:9091'

  grafana:
    image: grafana/grafana:6.0.2
    restart: always
    ports:
      - '3000:3000'